import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "@/providers/tanstack-query-provider";
import { KindeAuthProvider } from "@/providers/kinde-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import Sidebar from "@/components/sidebar/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Ripley Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-muted`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <KindeAuthProvider>
            <TanstackProvider>
              <main className="grid gap-4 p-4 grid-cols-[220px_1fr]">
                <Sidebar />
                {children}
              </main>
            </TanstackProvider>
          </KindeAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
